config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
end

app/models/article_category.rb
# frozen_string_literal: true
class ArticleCategory < ActiveRecord::Base
  belongs_to :category
  belongs_to :article
end

app/models/category.rb
# frozen_string_literal: true
class Category < ApplicationRecord
  validates :name, presence: true, length: { maximum: 20, minimum: 5 }
  validates_uniqueness_of :name
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

  validates :username,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }

  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { maximum: 105 },
            format: { with: URI::MailTo::EMAIL_REGEXP }

  has_many :articles

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  # before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was successfully created"
      redirect_to @article
    else
      render :new
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was successfully updated"
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:danger] = "You can only edit or delete your own articles"
      redirect_to @article
    end
  end

end

app/controllers/categories_controller.rb
# frozen_string_literal: true
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Category was successfully created.'
      redirect_to @category
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = 'Category was successfully updated.'
      redirect_to @category
    else
      render :edit
    end
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    unless logged_in? && current_user.admin?
      flash[:alert] = 'Only admins can perform that action.'
      redirect_to categories_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "You have successfully logged in"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have successfully logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to articles_path, :notice => "Welcome to the Alpha Blog #{user.username}, you have successfully signed up"
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, :notice => "Your account has been updated successfully"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    redirect_to root_path, :notice => "Account and all associated articles successfully deleted"
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      redirect_to @user, :alert => "You can only edit or delete your own account."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>By</th>
    <th colspan="3">Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.description %></td>
      <% if article.user %>
        <td><%= link_to article.user.username, user_path(article.user) %></td>
      <% end %>
      <%= if article.categories.any? %>
        <%= render article.categories %>
      <% end %>
      <td>
        <a href="<%= article_path(article) %>">Show</a>
      </td>
      <% if logged_in? and (article.user == current_user || current_user.admin?) %>
        <td>
          <a href="<%= edit_article_path(article) %>">Edit</a>
        </td>
        <td>
          <%= button_to 'Delete', article_path(article), method: :delete, data: { confirm: "Are you sure?" } %>
        </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/articles/_form.html.erb
<%= render "shared/errors", obj: @article %>
<%= form_with(model: @article, local: true) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :category %><br>
    <%= f.collection_select(:category_ids, Category.all, :id, :name,
                            { prompt: "Make your selection from the list below (can be empty)" }, { multiple: true, size: 3 }
        ) %>
  </p>
  <%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Edit article</title>
</head>
<body>
<h1>Edit article</h1>
<%= render partial: "form", locals: { article: @article } %>
<br>
<p>
  <%= link_to 'Cancel and return to articles listing', articles_path %>
</p>
</body>
</html>

app/views/articles/index.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>All Articles</title>
</head>
<body>
<h1>All Articles</h1>
<%= will_paginate @articles %>
<br>
<%= render 'article' %>
<br>
<p>
  <%= link_to 'Create New Article', new_article_path %>
</p>
</body>
</html>

app/views/articles/new.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Create new article</title>
</head>
<body>
<h1>Create a new article</h1>
<%= render "form" %>
<p>
  <%= link_to 'Return to articles listing', articles_path %>
</p>
</body>
</html>

app/views/articles/show.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Article details</title>
</head>
<body>

<h1>Title: <%= @article.title %></h1>
<p>Description: <%= @article.description %></p>
<p>By: <%= @article.user.username if @article.user %></p>
<%= link_to gravatar_for(@article.user, size: 150), user_path(@article.user) %>
<br>
<%= if @article.categories.any? %>
  <%= render @article.categories %>
<% end %>
<br>
<% if logged_in? and (@article.user == current_user || current_user.admin?) %>
  <p>
    <%= link_to 'Edit', edit_article_path(@article), class: 'button' %>
  </p>
  <p>
    <%= button_to 'Delete', article_path(@article), method: :delete, data: { confirm: "Are you sure?" } %>
  </p>
<% end %>

<p>
  <%= link_to 'Return to articles listing', articles_path %>
</p>
</body>
</html>

app/views/categories/_category.html.erb
<% link_to category.name, category_path(category) %>

app/views/categories/_form.html.erb
<%= render "shared/errors", obj: @category %>
<%= form_with(model: @category, local: true) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <%= f.submit %>
<% end %>

app/views/categories/edit.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Edit category</title>
</head>
<body>
<h1>Edit category</h1>
<%= render "shared/errors", obj: @category %>

<%= render partial: "form", locals: { category: @category } %>

<p>
  <%= link_to 'Return to category listing', category_path(@category) %>
</p>
</body>
</html>

app/views/categories/index.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>All Categories</title>
</head>
<body>
<h1>All Categories</h1>
<%= will_paginate @categories %>
<br>
<% @categories.each do |category| %>
  <tr>
    <td><%= link_to category.name, category_path(category) %></td>
    <td><%= pluralize(category.articles.count, "article") %> </td>
    <td>Created at: <%= category.created_at %></td>
    <td>Edited at: <%= time_ago_in_words(category.updated_at) %></td>
    <td>
      <a href="<%= category_path(category) %>">Show</a>
    </td>
  </tr>
<% end %>
<br>
<%= will_paginate @categories %>
<br>
<p>
  <%= link_to 'Create New Category', new_category_path %>
</p>

</body>
</html>

app/views/categories/new.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Create new category</title>
</head>
<body>
<h1>Create a new category</h1>
<%= render "shared/errors", obj: @category %>

<%= form_with(model: @category, local: true) do |f| %>
  <p>
    <%= f.label :name, "Category name" %><br>
    <%= f.text_field :name, placeholder: "Enter a name" %>
  </p>

  <%= f.submit %>
<% end %>
<p>
  <%= link_to 'Return to articles listing', articles_path %>
</p>
</body>
</html>

app/views/categories/show.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Category</title>
</head>
<body>
<h1>Category: <%= @category.name %></h1>
<br>
<% if logged_in? and current_user.admin? %>
  <%= button_to 'Edit category name', edit_category_path(@category) %>
<% end %>
<h3>Articles</h3>
<%= will_paginate @articles %>
<%= render 'articles/article' %>
</body>
</html>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <p class="notice"><%= msg %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
</head>

<body>
<%= render 'layouts/messages' %>
<%= yield %>
</body>
</html>

app/views/pages/about.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>About Page</title>
</head>
<body>
<h1>This is the about page</h1>
<br>
<p>
  <%= link_to 'Return to home page', root_path %>
</p>
</body>
</html>

app/views/pages/home.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Home Page</title>
</head>
<body>
<h1>This is the home page</h1>
<p>
  <%= link_to 'Return to articles listing', users_path %>
</p>
<p>
  <%= link_to 'Articles listing', articles_path %>
</p>

<p>
  <%= link_to 'About page', about_path %>
</p>

<% if logged_in? %>
  <a href="#">
    <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>
  </a>
  <p>
    <%= link_to current_user.username, user_path(current_user) %>
  </p>
  <p>
    <%= link_to "View your profile", user_path(current_user) %>
  </p>
  <p>
    <%= link_to "Edit your profile", edit_user_path(current_user) %>
  </p>
  <p>
    <%= link_to "Delete your profile", user_path(current_user), method: :delete %>
  </p>
  <p>
    <%= button_to 'Logout', logout_path, method: :delete %>
  </p>
<% else %>
  <p>
    <%= link_to 'Login', login_path %>
  </p>

  <p>
    <%= link_to 'Sign up', signup_path %>
  </p>
<% end %>

<a href="#"> Categories</a>
<% if logged_in? && current_user.admin? %>
<%= link_to "Create new category", new_category_path %>
<% end %>

<%= link_to "View categories", categories_path %>
</body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <h2>The following errors prevented the <%= obj.class.name.downcase %> from being saved</h2>
  <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/users/_form.html.erb
<%= render "shared/errors", obj: @user %>

<%= form_with(model: @user, local: true) do |f| %>
  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username, placeholder: "Enter your username" %>
  </p>
  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email, placeholder: "Enter your email address" %>
  </p>
  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password, placeholder: "Choose a password" %>
  </p>
  <%= f.submit(@user.new_record? ? "Sign Up" : "Update Account") %>
<% end %>

app/views/users/edit.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Edit profile</title>
</head>
<body>
<h1>Edit your profile</h1>
<%= render "form" %>
<p>
  <%= link_to 'Return to your profile', user_path(@user) %>
</p>
</body>
</html>

app/views/users/index.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Alpha Bloggers</title>
</head>
<body>
<h1>Alpha bloggers</h1>
<%= will_paginate @users %>
<br>
<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>By</th>
    <th>Articles written</th>
    <th>Joined</th>
    <th colspan="3">Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td>
        <%= link_to gravatar_for(user, size: 150), user %>
      </td>
      <td><%= link_to user.username, user %></td>
      <td><%= user.email %></td>
      <td>
        <%= pluralize(user.articles.count, "article") %>
      </td>
      <td>
        Joined <%= time_ago_in_words(user.created_at) %>
      </td>
      <% if logged_in? %>
        <%= if user == current_user %>
          <td>
            <%= link_to "Edit profile", edit_user_path(user) %>
          </td>
        <% end %>
        <%= if current_user.admin? %>
          <td>
            <%= button_to "Delete user", user_path(user), method: :delete %>
          </td>
        <% end %>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>
<p>
  <%= link_to 'Return to articles listing', articles_path %>
</p>
</body>
</html>

app/views/users/new.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Create new user</title>
</head>
<body>
<h1>Create a new user</h1>
<%= render "form" %>
<p>
  <%= link_to 'Return to articles listing', articles_path %>
</p>
</body>
</html>

app/views/users/show.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Profile Details</title>
</head>
<body>
<h1><%= @user.username %> profile</h1>
<br>
<% if logged_in? %>
  <p>
    <%= button_to 'Logout', logout_path, method: :delete %>
  </p>
<% end %>

<br>
<%= gravatar_for @user, size: 200 %>
<br>
<% if logged_in? and @user == current_user %>
  <p><%= link_to 'Edit your profile', edit_user_path(@user) %></p>
<% end %>
<h3>Articles</h3>
<%= will_paginate @articles %>
<%= render 'articles/article' %>
</body>
</html>